import { useState } from "react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { marked } from "marked";

marked.setOptions({ breaks: true, gfm: true });

function parseMarkdown(raw = "") {
  return marked.parse(raw);
}


const MinutesDocument = ({ html }) => {
  return (
    <div
      style={{
        width: "794px",
        background: "#f8fafc",
        fontFamily: "Plus Jakarta Sans, sans-serif",
        color: "#1e293b",
      }}
    >
      {/* HEADER */}
      <div
        style={{
          background: "linear-gradient(135deg, #0e7490, #1d4ed8)",
          color: "#fff",
          padding: "40px",
        }}
      >
        <h1 style={{ margin: 0 }}>Meeting Minutes</h1>
        <p style={{ opacity: 0.7 }}>
          AI Generated Summary · {new Date().toLocaleDateString()}
        </p>
      </div>

      {/* CONTENT */}
      <div style={{ padding: "40px" }}>
        <div
          dangerouslySetInnerHTML={{ __html: html }}
          style={{
            lineHeight: 1.7,
            fontSize: "14px",
          }}
        />
      </div>

      {/* FOOTER */}
      <div
        style={{
          padding: "20px 40px",
          background: "#0f172a",
          color: "#94a3b8",
          fontSize: "12px",
        }}
      >
        Generated by AI · Confidential
      </div>
    </div>
  );
};

const MeetingMinutes = () => {
  const BASE_URL = "http://127.0.0.1:5000";

  const [file, setFile] = useState(null);
  const [minutes, setMinutes] = useState("");
  const [loading, setLoading] = useState(false);
  const [exporting, setExporting] = useState(false);
  const [error, setError] = useState("");

  /* FILE CHANGE */
  const handleFileChange = (e) => {
    setFile(e.target.files[0]);
    setMinutes("");
    setError("");
  };

  /* UPLOAD AUDIO */
  const handleUpload = async () => {
    if (!file) {
      setError("Please select an audio file.");
      return;
    }

    try {
      setLoading(true);
      setError("");

      const formData = new FormData();
      formData.append("audio", file);

      const res = await fetch(`${BASE_URL}/api/meeting-minutes`, {
        method: "POST",
        body: formData,
      });

      const data = await res.json();

      if (!res.ok) throw new Error(data.error || "Something went wrong");

      setMinutes(data.minutes);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  /* EXPORT PDF (Styled) */
  const handleDownloadPDF = async () => {
    setExporting(true);

    const element = document.getElementById("minutes-pdf");

    const canvas = await html2canvas(element, {
      scale: 2.5,
      useCORS: true,
      backgroundColor: "#f8fafc",
    });

    const pdf = new jsPDF("p", "mm", "a4");

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();

    const imgWidth = pageWidth;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    const imgData = canvas.toDataURL("image/png");

    let y = 0;

    while (y < imgHeight) {
      if (y > 0) pdf.addPage();
      pdf.addImage(imgData, "PNG", 0, -y, imgWidth, imgHeight);
      y += pageHeight;
    }

    pdf.save("meeting_minutes.pdf");
    setExporting(false);
  };

  /* UI STYLES */
  const styles = {
    container: {
      minHeight: "100vh",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      background: "#091413",
    },
    card: {
      background: "#ffffff08",
      padding: "2rem",
      borderRadius: "16px",
      width: "500px",
      border: "1px solid #b0e4cc14",
      backdropFilter: "blur(10px)",
      color: "#fff",
    },
    title: {
      color: "#B0E4CC",
      marginBottom: "1rem",
    },
    input: {
      marginBottom: "1rem",
      width: "100%",
    },
    button: {
      padding: "0.8rem",
      borderRadius: "8px",
      background: "#408A71",
      color: "#fff",
      border: "none",
      cursor: "pointer",
      width: "100%",
    },
    error: {
      color: "red",
      marginTop: "1rem",
    },
    resultContainer: {
      marginTop: "2rem",
    },
    minutesBox: {
      background: "#00000066",
      padding: "1rem",
      borderRadius: "10px",
      maxHeight: "300px",
      overflowY: "auto",
      marginBottom: "1rem",
    },
    downloadBtn: {
      padding: "0.7rem",
      borderRadius: "8px",
      background: "#285A48",
      color: "#fff",
      border: "none",
      cursor: "pointer",
      width: "100%",
    },
  };

  return (
    <>
      <div style={styles.container}>
        <div style={styles.card}>
          <h2 style={styles.title}>AI Meeting Minutes Generator</h2>

          <input
            type="file"
            accept="audio/mp3"
            onChange={handleFileChange}
            style={styles.input}
          />

          <button onClick={handleUpload} style={styles.button}>
            {loading ? "Processing..." : "Generate Minutes"}
          </button>

          {error && <p style={styles.error}>{error}</p>}

          {minutes && (
            <div style={styles.resultContainer}>
              <h3>Meeting Minutes</h3>
              <div style={styles.minutesBox}>
                <div
                  dangerouslySetInnerHTML={{
                    __html: parseMarkdown(minutes),}}
                />
              </div>

              <button
                onClick={handleDownloadPDF}
                style={styles.downloadBtn}
                disabled={exporting}
              >
                {exporting ? "Exporting..." : "Download PDF"}
              </button>
            </div>
          )}
        </div>
      </div>

      {/* HIDDEN PDF TARGET */}
      <div
        id="minutes-pdf"
        style={{
          position: "absolute",
          left: "-9999px",
          top: 0,
          width: "794px",
        }}
      >
        <MinutesDocument html={parseMarkdown(minutes)} />
      </div>
    </>
  );
};

export default MeetingMinutes;